### ISSUE TITLE
License

### ISSUE THREAD

**Issue by leftshift** [lukaskollmer/mvg-node#1]
Hey, cool project!
However, it seems to be at least partially based on code from https://github.com/leftshift/python_mvg_api (indicated by similarities in the code and the fact you forked it a day before publishing this).
My project is also licensed under the MIT license, so what you did is totally fine (and encouraged! Thanks!) as long as you include the original copyright notice (=my name).
It'd be great if you could do that, thanks!

**Comment by lukaskollmer** [comment]
Sure, I'll mention your project in the readme!

**Comment by leftshift** [comment]
Great, thanks!

**Comment by lukaskollmer** [comment]
Here you go: https://github.com/lukaskollmer/mvg-node/commit/405b1e7ddcf627da3a90a30164e0a9ca60543185
