### ISSUE TITLE
Update on NPM?

### ISSUE THREAD

**Issue by lostdesign** [lukaskollmer/mvg-node#8]
Since #4 was merged, it'd be nice to update the package on NPM. Maybe something like this https://sergiodxa.com/articles/github-actions-npm-publish/ would be helpful?

**Comment by henrik-muehe** [comment]
I second this, that would actually make this helpful! Thanks in advance!

**Comment by henrik-muehe** [comment]
For reference,

`
"mvg-node": "git@github.com:lukaskollmer/mvg-node.git",
`

This in package.json apparently works for the moment.

**Comment by lukaskollmer** [comment]
@henrik-muehe I published a new version to NPM (1.2.4)

@lostdesign sry I never replied to this i probably missed the email when you opened the issue...

**Comment by henrik-muehe** [comment]
Thanks a bunch!

**Comment by lostdesign** [comment]
@lukaskollmer no worries, thanks @henrik-muehe for bringing this up again 👍
